from __future__ import annotations

import subprocess
from pathlib import Path


def write_import_render_script(
    output_jsx: Path,
    xml_path: Path,
    srt_path: Path | None = None,
    export_path: Path | None = None,
    encoder_preset: Path | None = None,
) -> Path:
    output_jsx.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Generated by Premiere-Pro-edit-bibl-windows. */",
        "(function () {",
        "  app.enableQE();",
        "  if (!app.project) { app.newProject('bibl_windows_auto_project.prproj'); }",
        f"  var xmlFile = new File({jsx_string(xml_path.resolve())});",
        "  if (!xmlFile.exists) { throw new Error('XML file does not exist: ' + xmlFile.fsName); }",
        "  app.project.importFiles([xmlFile.fsName], true, app.project.rootItem, false);",
    ]
    if srt_path is not None:
        lines += [
            f"  var srtFile = new File({jsx_string(srt_path.resolve())});",
            "  if (srtFile.exists) { app.project.importFiles([srtFile.fsName], true, app.project.rootItem, false); }",
        ]
    if export_path is not None:
        lines += [
            "  var seq = app.project.activeSequence;",
            "  if (!seq) { throw new Error('No active sequence after XML import. Open the imported sequence and rerun export.'); }",
            f"  var outFile = new File({jsx_string(export_path.resolve())});",
            "  if (!outFile.parent.exists) { outFile.parent.create(); }",
        ]
        if encoder_preset is not None:
            lines += [
                f"  var presetFile = new File({jsx_string(encoder_preset.resolve())});",
                "  if (!presetFile.exists) { throw new Error('Encoder preset does not exist: ' + presetFile.fsName); }",
                "  app.encoder.launchEncoder();",
                "  app.encoder.encodeSequence(seq, outFile.fsName, presetFile.fsName, app.encoder.ENCODE_WORKAREA, 1);",
                "  app.encoder.startBatch();",
            ]
        else:
            lines += [
                "  seq.exportAsMediaDirect(outFile.fsName, '', app.encoder.ENCODE_WORKAREA);",
            ]
    lines += [
        "})();",
        "",
    ]
    output_jsx.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return output_jsx


def find_premiere_executable(explicit: Path | None = None) -> Path | None:
    if explicit is not None:
        candidate = explicit.resolve()
        return candidate if candidate.exists() else None
    roots = [
        Path(r"C:\Program Files\Adobe"),
        Path(r"C:\Program Files (x86)\Adobe"),
    ]
    names = [
        "Adobe Premiere Pro 2026",
        "Adobe Premiere Pro 2025",
        "Adobe Premiere Pro 2024",
        "Adobe Premiere Pro 2023",
    ]
    for root in roots:
        for name in names:
            exe = root / name / "Adobe Premiere Pro.exe"
            if exe.exists():
                return exe
    return None


def launch_premiere(
    premiere_exe: Path,
    xml_path: Path | None = None,
    script_path: Path | None = None,
) -> subprocess.Popen:
    args = [str(premiere_exe)]
    if script_path is not None:
        args += ["-r", str(script_path.resolve())]
    elif xml_path is not None:
        args.append(str(xml_path.resolve()))
    return subprocess.Popen(args)


def jsx_string(path: Path) -> str:
    text = str(path).replace("\\", "/")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'
